# SPDX-FileCopyrightText: 2023 Timur Ismagilov <https://bouncepaw.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

image: alpine/edge
packages:
  - go
  - curl
sources:
  - https://git.sr.ht/~bouncepaw/betula
tasks:
  - test: |
      cd betula
      make test
