# SPDX-FileCopyrightText: 2025 Danila Gorelko
#
# SPDX-License-Identifier: AGPL-3.0-only

name: build
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build
        run: go build -v ./...