# SPDX-FileCopyrightText: 2025 Danila Gorelko
#
# SPDX-License-Identifier: AGPL-3.0-only

name: test
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Test
        run: |
          mkdir -p coverage
          go test -race -coverprofile=coverage/coverage.txt -covermode=atomic -coverpkg=./... ./...
          go tool cover -html=coverage/coverage.txt -o coverage/coverage.html
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
