# SPDX-FileCopyrightText: 2022-2025 Betula contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

name: test
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Test
        run: go test ./...