# SPDX-FileCopyrightText: 2026 Danila Gorelko
# SPDX-FileCopyrightText: 2026 Timur Ismagilov <https://bouncepaw.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

when:
  event: [tag]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: golang:1.24.13
    environment:
      CGO_ENABLED: 0
      PLATFORMS:
        - linux/amd64
        - linux/arm64
        - darwin/amd64
        - darwin/arm64
        - openbsd/amd64
        - openbsd/arm64
        - netbsd/amd64
        - netbsd/arm64
        - plan9/amd64
        - windows/amd64
        - windows/arm64
        - freebsd/amd64
        - freebsd/arm64
    commands:
      - mkdir -p dist
      - |
        IFS=,
        for platform in $PLATFORMS; do
          platform=$(echo "$platform" | tr -d ' ')
          GOOS=$(echo "$platform" | cut -d/ -f1)
          GOARCH=$(echo $platform | cut -d/ -f2)

          echo "building $GOOS/$GOARCH"

          EXT=""
          [ "$GOOS" = "windows" ] && EXT=".exe"

          GOOS=$GOOS GOARCH=$GOARCH go build \
            -ldflags "-s -w" \
            -o dist/betula-$GOOS-$GOARCH$EXT \
            ./cmd/betula
        done

  - name: release
    image: woodpeckerci/plugin-release
    depends_on:
      - build
    settings:
      api_key:
        from_secret: woodpecker-release
      files:
        - dist/*
      title: Betula release ${CI_COMMIT_TAG}
      note: "Automated release of binaries"
      draft: true
