# SPDX-FileCopyrightText: 2026 Vitaly Chekushkin
#
# SPDX-License-Identifier: AGPL-3.0-only

when:
  event: [tag]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  build-publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: index.docker.io
      repo: bouncepaw/betula
      platforms:
        - linux/arm/v7
        - linux/arm64/v8
        - linux/amd64
      tags:
        - ${CI_COMMIT_TAG}
        - latest
      docker-config-json:
        from_secret: REPO_PUSH_CONFIG_JSON
